#If BLACKLIST, the list below will be treated as a blacklist what not to touch.
#If WHITELIST, the will be treated as a whitelist what biomes should only be touched
#Allowed Values: WHITELIST, BLACKLIST
listMode = "BLACKLIST"
#The blacklist or whitelist, depending on listMode
biomeList = []
#The downfall value each biome should get. If -1, EternalWinter will keep the original downfall of the biome, otherwise it takes a value between 0 and 1
#Range: -1.0 ~ 1.0
downfall = -1.0

