
[maid]
	#The item that can tamed maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidTamedItem = "minecraft:cake"
	#The item that can temptation maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidTemptationItem = "minecraft:cake"
	#The item that can NTR maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidNtrItem = "minecraft:structure_void"
	#The max range of maid home mode
	#Range: 3 ~ 64
	MaidHomeRange = 8
	#Maid can switch models freely
	MaidChangeModel = true
	#The maximum number of maids the player own
	#Range: > 0
	OwnerMaxMaidNum = 2147483647
	#The entity that the maid will not hurt when in ranged attack
	MaidRangedAttackIgnore = []

[chair]
	#Chair can switch models freely
	ChairChangeModel = true
	#Chair can be destroyed by anyone
	ChairCanDestroyedByAnyone = true

[misc]
	#Maid fairy's power point
	#Range: 0.0 ~ 5.0
	MaidFairyPowerPoint = 0.16
	#Maid fairy's spawn probability (zombie is 100, enderman is 10)
	#Range: > 0
	MaidFairySpawnProbability = 70
	#The following biome do not spawn maid fairy
	MaidFairyBlacklistBiome = ["minecraft:plains", "minecraft:sunflower_plains", "minecraft:snowy_plains", "minecraft:ice_spikes", "minecraft:desert", "minecraft:swamp", "minecraft:mangrove_swamp", "minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:dark_forest", "minecraft:old_growth_birch_forest", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "minecraft:taiga", "minecraft:snowy_taiga", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:windswept_hills", "minecraft:windswept_gravelly_hills", "minecraft:windswept_forest", "minecraft:windswept_savanna", "minecraft:jungle", "minecraft:sparse_jungle", "minecraft:bamboo_jungle", "minecraft:badlands", "minecraft:eroded_badlands", "minecraft:wooded_badlands", "minecraft:meadow", "minecraft:cherry_grove", "minecraft:grove", "minecraft:snowy_slopes", "minecraft:frozen_peaks", "minecraft:jagged_peaks", "minecraft:stony_peaks", "minecraft:river", "minecraft:frozen_river", "minecraft:beach", "minecraft:snowy_beach", "minecraft:stony_shore", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:ocean", "minecraft:deep_ocean", "minecraft:cold_ocean", "minecraft:deep_cold_ocean", "minecraft:frozen_ocean", "minecraft:deep_frozen_ocean", "minecraft:mushroom_fields", "minecraft:dripstone_caves", "minecraft:lush_caves", "minecraft:deep_dark"]
	#The following dimension do not spawn maid fairy
	MaidFairyBlacklistDimension = ["minecraft:the_nether", "minecraft:the_end", "twilightforest:twilight_forest"]
	#Loss power point after player death
	#Range: 0.0 ~ 5.0
	PlayerDeathLossPowerPoint = 1.0
	#Give a soul spell item for player first join
	GiveSoulSpell = true
	#Shrine Lamp Effect Cost (Power Point/Per Hour)
	#Range: 0.0 ~ 1.7976931348623157E308
	ShrineLampEffectCost = 0.9
	#Shrine Lamp Max Storage Power Point
	#Range: 0.0 ~ 1.7976931348623157E308
	ShrineLampMaxStorage = 100.0
	#Shrine Lamp Max Range Of Absorb Power Point
	#Range: > 0
	ShrineLampMaxRange = 6
	#Give the Memorizable Gensokyo book item for player first join
	GivePatchouliBook = true

[vanilla]
	#Whether to replace the vanilla slime model with the yukkuri.
	ReplaceSlimeModel = false
	#Whether to replace the vanilla xp orb texture with the point items.
	ReplaceXPTexture = false
	#Whether to replace the vanilla totem texture with the life point.
	ReplaceTotemTexture = false
	#Whether to replace the vanilla bottle of xp texture with the point items.
	ReplaceXPBottleTexture = false

